### ISSUE TITLE
Add disclaimer about what you are logging to your analytics

### ISSUE THREAD

**Issue by chill-cod3r** [MariusAlch/vscode-json-to-ts#16]
I was a bit surprised to find this code here:

https://github.com/MariusAlch/vscode-json-to-ts/blob/master/src/lib.ts#L45

You’re actually logging out the first 250 characters of whatever JSON someone is using this extension for. Sure, anyone can look at the code as I have and see that you’re doing it. However imo you should put a disclaimer somewhere so that people can be cautioned to not put sensitive JSON in here - it’s unfortunately not obvious to everyone. 
This plugin has 297k downloads, that’s a lot of JSON data going to your analytics server. Vscode has plenty of anonymous ways to log telemetry data and imo this goes outside the bounds of that.

**Comment by markuspeitl** [comment]
@wolfejw86 Wow thanks for the info, almost installed the extension.
Quite unethical to to do this (Some people might unknowingly leak sensitive information with this)
I am no lawyer, but i am pretty sure it is at least illegal in the EU as it violates the GDPR.

**Comment by rentolo-zzimick** [comment]
@wolfejw86 @markuspeitl what do you think if I create another extension without this logging and with improvements like to work for other languages too, support single type output (without extracting sub type definitions)?

**Comment by rentolo-zzimick** [comment]
Also we can collaborate on it if you guys want 😀

**Comment by MariusAlch** [comment]
I've added this initially just to see how people are using the extension. Removed this all together with version 1.8.0
