### ISSUE TITLE
add an option for I prefix interface

### ISSUE THREAD

**Issue by broven** [MariusAlch/vscode-json-to-ts#7]
![image](https://user-images.githubusercontent.com/12854613/65831972-a2553680-e2f1-11e9-8507-079d61de327e.png)

I enabled this common eslint rule, can we add a option, to generate interface name with I prefixd?

**Comment by AKclown** [comment]
I recommend my plugin to solve this problem. [JS TO TS](https://github.com/AKclown/js-to-ts)
