### ISSUE TITLE
No me funciona bien

### ISSUE THREAD

**Issue by bryancarias** [MariusAlch/vscode-json-to-ts#8]
cuando intento hacer el pegado del Json ya copiado me dice lo siguiente:

Command failed: cscript /Nologo \.vscode\extensions\mariusalchimavicius.json-to-ts-1.5.5\node_modules\copy-paste\platform\fallbacks\paste.vbs

No se a que se deba este error.

**Comment by umblexysalonso** [comment]
hola amigo dime si pudiste corregir el error ?
