### ISSUE TITLE
can't work on vscode about Version: 1.44.0-insider

### ISSUE THREAD

**Issue by zhusjfaker** [MariusAlch/vscode-json-to-ts#9]
The command does not contain JSON to TS

![image](https://user-images.githubusercontent.com/31839470/76781219-59366780-67e9-11ea-840d-9009500039e2.png)

**Comment by l1nyanm1ng** [comment]
I meet the same too, that's crazy, I've spend about 30 minutes to resolve it, and see this issue. That must be caused by the new version's vscode.

**Comment by Ende93** [comment]
Seem like vscode changed `commands config of package.json` but I did not found that commit or log), You can use `Selection` and `Do some refactoring` now, not `clipboard` or `jsonTo...`.

**Comment by MariusAlch** [comment]
Looking into this...

**Comment by MariusAlch** [comment]
Thanks for bringing this up, the extension should be fixed now.
